const HERO_DISPLAY_NAMES = {
  antimage: 'Anti-Mage',
  queenofpain: 'Queen of Pain',
  nevermore: 'Shadow Fiend',
  zuus: 'Zeus',
  rattletrap: 'Clockwerk',
  furion: "Nature's Prophet",
  necrolyte: 'Necrophos',
  windrunner: 'Windranger',
  magnataur: 'Magnus',
  vengefulspirit: 'Vengeful Spirit',
  skeleton_king: 'Wraith King',
  obsidian_destroyer: 'Outworld Destroyer',
  doom_bringer: 'Doom',
  treant: 'Treant Protector',
  life_stealer: 'Lifestealer',
  abyssal_underlord: 'Underlord',
  batrider: 'Batrider',
  bloodseeker: 'Bloodseeker',
  beastmaster: 'Beastmaster',
  broodmother: 'Broodmother',
  earthshaker: 'Earthshaker',
  enigma: 'Enigma',
  huskar: 'Huskar',
  jakiro: 'Jakiro',
  kunkka: 'Kunkka',
  leshrac: 'Leshrac',
  lycan: 'Lycan',
  omniknight: 'Omniknight',
  sniper: 'Sniper',
  tinker: 'Tinker',
  weaver: 'Weaver',
  invoker: 'Invoker',
  visage: 'Visage',
  pugna: 'Pugna',
  ursa: 'Ursa',
  warlock: 'Warlock',
  slardar: 'Slardar',
  tidehunter: 'Tidehunter',
  viper: 'Viper',
  lina: 'Lina',
  lion: 'Lion',
  enigma: 'Enigma',
  disruptor: 'Disruptor',
  silencer: 'Silencer',
  rubick: 'Rubick',
  bane: 'Bane',
  razor: 'Razor',
  riki: 'Riki',
  meepo: 'Meepo',
  abaddon: 'Abaddon',
  wisp: 'Io',
  shredder: 'Timbersaw',
  skywrath_mage: 'Skywrath Mage',
  legion_commander: 'Legion Commander',
  phoenix: 'Phoenix',
  oracle: 'Oracle',
  techies: 'Techies',
  pangolier: 'Pangolier',
  dark_willow: 'Dark Willow',
  grimstroke: 'Grimstroke',
  void_spirit: 'Void Spirit',
  snapfire: 'Snapfire',
  mars: 'Mars',
  hoodwink: 'Hoodwink',
  dawnbreaker: 'Dawnbreaker',
  marci: 'Marci',
  primal_beast: 'Primal Beast',
  muerta: 'Muerta',
};

export function formatHeroName(raw) {
  if (!raw) return '—';
  const slug = raw.replace(/^npc_dota_hero_/, '');
  if (HERO_DISPLAY_NAMES[slug]) return HERO_DISPLAY_NAMES[slug];
  return slug
    .replace(/_/g, ' ')
    .replace(/\b\w/g, c => c.toUpperCase());
}
