// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/oa-revamp/EditorialAlmanac.tsx": () => import("../components/mockups/oa-revamp/EditorialAlmanac.tsx"),
  "./components/mockups/oa-revamp/EditorialBroadsheet.tsx": () => import("../components/mockups/oa-revamp/EditorialBroadsheet.tsx"),
  "./components/mockups/oa-revamp/EditorialNavy.tsx": () => import("../components/mockups/oa-revamp/EditorialNavy.tsx"),
  "./components/mockups/oa-revamp/EditorialYachtClub.tsx": () => import("../components/mockups/oa-revamp/EditorialYachtClub.tsx"),
  "./components/mockups/oa-revamp/HybridCourtPitch.tsx": () => import("../components/mockups/oa-revamp/HybridCourtPitch.tsx"),
  "./components/mockups/oa-revamp/HybridNewsroom.tsx": () => import("../components/mockups/oa-revamp/HybridNewsroom.tsx"),
  "./components/mockups/oa-revamp/HybridPressBox.tsx": () => import("../components/mockups/oa-revamp/HybridPressBox.tsx"),
  "./components/mockups/oa-revamp/MinimalPro.tsx": () => import("../components/mockups/oa-revamp/MinimalPro.tsx"),
  "./components/mockups/oa-revamp/TacticalBroadcast.tsx": () => import("../components/mockups/oa-revamp/TacticalBroadcast.tsx"),
  "./components/mockups/oa-revamp/TacticalCyber.tsx": () => import("../components/mockups/oa-revamp/TacticalCyber.tsx"),
  "./components/mockups/oa-revamp/TacticalEsports.tsx": () => import("../components/mockups/oa-revamp/TacticalEsports.tsx"),
  "./components/mockups/oa-revamp/TacticalRadiantDire.tsx": () => import("../components/mockups/oa-revamp/TacticalRadiantDire.tsx"),
  "./components/mockups/profile-redesign/MagazineSpread.tsx": () => import("../components/mockups/profile-redesign/MagazineSpread.tsx"),
  "./components/mockups/profile-redesign/TacticalDossier.tsx": () => import("../components/mockups/profile-redesign/TacticalDossier.tsx"),
  "./components/mockups/profile-redesign/TrophyWall.tsx": () => import("../components/mockups/profile-redesign/TrophyWall.tsx")
};
