// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/oa-revamp/EditorialNavy.tsx": () => import("../components/mockups/oa-revamp/EditorialNavy.tsx"),
  "./components/mockups/oa-revamp/MinimalPro.tsx": () => import("../components/mockups/oa-revamp/MinimalPro.tsx"),
  "./components/mockups/oa-revamp/TacticalEsports.tsx": () => import("../components/mockups/oa-revamp/TacticalEsports.tsx")
};
