import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import { buildHighlightItems, recapPerformerName } from '../utils/recapHighlights';

// /this-week — the AI-generated weekly recap, surfaced on the site.
// The recap itself is generated by the Discord weekly cron in src/discord/bot.js
// (Mondays) which calls db.saveWeeklyRecap after generateWeeklyRecapBlurb.
// We read whatever the latest cached one is from /api/latest-recap.
//
// This page is intentionally read-only — no "regenerate" button here (the
// admin panel already has /generate-recap behind the admin auth middleware).
export default function ThisWeek() {
  const [recap, setRecap] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    let cancelled = false;
    setLoading(true);
    fetch('/api/latest-recap')
      .then(r => r.ok ? r.json() : Promise.reject(new Error('Failed to load recap')))
      .then(d => { if (!cancelled) setRecap(d && d.generated_at ? d : null); })
      .catch(e => { if (!cancelled) setError(e.message); })
      .finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, []);

  const ago = recap?.generated_at
    ? new Date(recap.generated_at).toLocaleString('en-AU', { dateStyle: 'medium', timeStyle: 'short' })
    : null;

  return (
    <div className="page-wrap" style={{ maxWidth: 880, margin: '0 auto', padding: '24px 16px' }}>
      <header style={{ marginBottom: 24 }}>
        <h1 className="page-title" style={{ margin: 0 }}>This week in inhouse</h1>
        <p style={{ color: 'var(--text-muted)', marginTop: 6, fontSize: 14 }}>
          AI-written recap of the past 7 days. Re-generated automatically every Monday and posted to Discord.
        </p>
      </header>

      {loading && (
        <div role="status" aria-live="polite" style={{ padding: 24, textAlign: 'center', color: 'var(--text-muted)' }}>
          Loading…
        </div>
      )}

      {error && !loading && (
        <div role="alert" style={{ padding: 16, border: '1px solid var(--accent-red, #f87171)', borderRadius: 8, color: 'var(--accent-red, #f87171)' }}>
          Couldn’t load this week’s recap: {error}
        </div>
      )}

      {!loading && !error && !recap && (
        <div style={{
          padding: 24, border: '1px solid var(--border)', borderRadius: 10,
          background: 'var(--bg-card)', color: 'var(--text-muted)', textAlign: 'center',
        }}>
          No recap yet. The first one is generated after the next Monday cron run.
        </div>
      )}

      {!loading && !error && recap && (
        <article style={{
          padding: 24, border: '1px solid var(--border)', borderRadius: 10,
          background: 'var(--bg-card)',
        }}>
          {ago && (
            <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 12 }}>
              Generated {ago} · {recap.matches_count || 0} match{recap.matches_count === 1 ? '' : 'es'}
            </div>
          )}

          {recap.ai_blurb && (
            <div style={{ fontSize: 16, lineHeight: 1.7, color: 'var(--text-primary)', marginBottom: 24, whiteSpace: 'pre-wrap' }}>
              {recap.ai_blurb}
            </div>
          )}

          {Array.isArray(recap.top_performers) && recap.top_performers.length > 0 && (
            <section style={{ marginTop: 24 }}>
              <h2 style={{ fontSize: 18, marginBottom: 12 }}>Top performers</h2>
              <ol style={{ paddingLeft: 20, margin: 0 }}>
                {recap.top_performers.slice(0, 5).map((p, i) => {
                  const kda = p.avg_kda != null ? Number(p.avg_kda).toFixed(2) : null;
                  const gpm = p.avg_gpm != null ? Math.round(Number(p.avg_gpm)) : null;
                  const statBits = [
                    kda != null ? `${kda} KDA` : null,
                    gpm != null ? `${gpm} GPM` : null,
                    p.games != null ? `${p.games} game${Number(p.games) === 1 ? '' : 's'}` : null,
                  ].filter(Boolean);
                  return (
                    <li key={p.account_id || i} style={{ marginBottom: 6, color: 'var(--text-primary)' }}>
                      {p.account_id ? (
                        <Link to={`/player/${p.account_id}`} style={{ color: 'var(--accent)', fontWeight: 600 }}>
                          {recapPerformerName(p)}
                        </Link>
                      ) : (
                        <span style={{ fontWeight: 600 }}>{recapPerformerName(p)}</span>
                      )}
                      {p.summary
                        ? <span style={{ color: 'var(--text-muted)' }}> — {p.summary}</span>
                        : statBits.length > 0 && <span style={{ color: 'var(--text-muted)' }}> — {statBits.join(' · ')}</span>}
                    </li>
                  );
                })}
              </ol>
            </section>
          )}

          {(() => {
            const items = buildHighlightItems(recap.fun_highlights);
            if (items.length === 0) return null;
            return (
              <section style={{ marginTop: 24 }}>
                <h2 style={{ fontSize: 18, marginBottom: 12 }}>Fun highlights</h2>
                <ul style={{ paddingLeft: 20, margin: 0, color: 'var(--text-secondary)' }}>
                  {items.map((item) => (
                    <li key={item.key} style={{ marginBottom: 6, lineHeight: 1.6 }}>
                      <strong style={{ color: 'var(--text-primary)' }}>{item.label}:</strong>{' '}
                      <span>{item.body}</span>
                    </li>
                  ))}
                </ul>
              </section>
            );
          })()}
        </article>
      )}
    </div>
  );
}
